(function($){
    $(function(){
        $('#list').on('click','li',function(){
            $('li.active').removeClass('active');
            $(this).addClass('active');
            $('div.active').removeClass('active');
            $('div.articles').eq($(this).index()).addClass('active');
        });
    });
})(jQuery);